EXPERIMENT:
  NAME: ""
  TAG: "e240-dkd-vgg8"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "DKD"
  TEACHER: "ResNet50"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

# CUDA_VISIBLE_DEVICES=3 python3 tools/train.py --cfg configs/cifar100/dkd/dkd.yaml