EXPERIMENT:
  NAME: ""
  TAG: "vanilla_25"
  PROJECT: "vanilla_baselines"

DATASET:
  TYPE: "cifar100_fewshot"
  NUM_WORKERS: 4
  TEST:
    BATCH_SIZE: 64

DISTILLER:
  TYPE: "NONE"
  TEACHER: "resnet32x4"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
