EXPERIMENT:
  NAME: ""
  TAG: "ckd,res50,mobilenetv1"
  PROJECT: "imagenet_baselines"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "CKD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV1"
SOLVER:
  BATCH_SIZE: 512
  EPOCHS: 200
  LR: 0.2
  LR_COSINE: True
  LR_COSINE_MIN: 0.0
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
CKD:
  CE_WEIGHT: 1.0
  CL_WEIGHT: 10.0
  TEMPERATURE: 1.0
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
  WANDB : False

# CUDA_VISIBLE_DEVICES=2 python3 tools/train.py --cfg configs/imagenet/r34_r18/ckd.yaml


