EXPERIMENT:
  NAME: ""
  TAG: "ckd,res110,res32"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "CKD"
  TEACHER: "resnet110"
  STUDENT: "resnet32"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 480
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  LR_COSINE: True
  LR_COSINE_MIN: 0.0
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
CKD:
  CE_WEIGHT: 1.0
  CL_WEIGHT: 10.0
  TEMPERATURE: 1.0
  
LOG:
  WANDB : False 
