_BASE_: "../Base-Distillation.yaml"
OUTPUT_DIR: output/ReviewDKD-R50-R101-Mask
# OUTPUT_DIR: mnt/nas-resource-linkdata/ckd/detection_output/dkd/ReviewDKD-R50-R101-Mask/
MODEL:
  MASK_ON: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone_kd"
  WEIGHTS: "pretrained/r50-r101mask.pth"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  ROI_HEADS:
    NAME: "StandardROIHeads"

TEACHER:
  MODEL:
    RESNETS:
      DEPTH: 101
KD:
  TYPE: "ReviewDKD"
  REVIEWKD:
    LOSS_WEIGHT: 1.0

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  # MAX_ITER: 180000
  # STEPS:
  # - 120000
  # - 160000
  MAX_ITER: 360000
  STEPS:
  - 240000
  - 320000


#  CUDA_VISIBLE_DEVICES=0,1 python3 train_net.py --config-file configs/DKD/ReviewDKD-R50-R101-Mask.yaml --num-gpus 2 --dist-url tcp://127.0.0.1:8080