EXPERIMENT:
  NAME: ""
  TAG: "ofd,r34_r18,epoch100"
  PROJECT: "places_baselines"
DATASET:
  TYPE: "places365"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "OFD"
  TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 100
  LR: 0.05
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"
OFD:
  LOSS:
    FEAT_WEIGHT: 0.0001
LOG:
  TENSORBOARD_FREQ: 50
  SAVE_CHECKPOINT_FREQ: 10
