EXPERIMENT:
  NAME: ""
  TAG: "places_r18"
  PROJECT: "places_vanilla"

DATASET:
  TYPE: "places365"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128

DISTILLER:
  TYPE: "NONE"
  # TEACHER: "ResNet34"
  STUDENT: "ResNet18"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"


# CUDA_VISIBLE_DEVICES=6 python3 tools/train.py --cfg configs/places365/vanilla/r18.yaml
# CUDA_VISIBLE_DEVICES=6 python3 tools/train.py --cfg configs/places365/vanilla/r18.yaml
