EXPERIMENT:
  NAME: ""
  TAG: "places_r50"
  PROJECT: "places_vanilla"

DATASET:
  TYPE: "places365"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128

DISTILLER:
  TYPE: "NONE"
  # TEACHER: "ResNet50"
  STUDENT: "ResNet50"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"



# CUDA_VISIBLE_DEVICES=2,3 python3 tools/train.py --cfg configs/places365/vanilla/r50.yaml
